### ISSUE TITLE
Looking for help with extra BattleLobby info

### ISSUE THREAD

**Issue by MGatner** [koliva8245/Heroes.ReplayParser#17]
Hi koliva- I'm updating my BattleLobby parser for live games. Currently it only grabs BattleTags and region, but the disordered nature of players & observers means that isn't enough to determine who is actually in the game. I was trying to parse out some fo the extra data in the middle of the TIds and BattleTags comparing it with your merge of Heroes.ReplayParser but I often can't get the bits to line up consistently (e.g. finding the collection size again https://github.com/koliva8245/Heroes.ReplayParser/blob/27838560be8e08c3ba524a1cb99968769d334fa2/Heroes.ReplayParser/MPQFiles/ReplayServerBattlelobby.cs#L197) (e.g.2 party bit often doesn't seem right).
I was wondering if you could direct me to how you figured out bit string values (like "m_hasVoiceSilencePenalty") and if there's a way to get a fresh set of that from a new patch replay.

**Comment by koliva8245** [comment]
Parsing out the battlelobby is mostly just guessing and checking.  Some things like `m_isBlizzardStaff` or the account level have been confirmed. `m_hasVoiceSilencePenalty` is one that I actually never confirmed to be 100% sure since I have never seen someone voice silenced.  It may be actually be the bit before. New data to be found is just added when new patches come out as the parsing of the battlelobby fails.

The best way to be sure the bits line up correctly is to check if you can parse out the battletag strings.

For the current patch (and like 4 previous ones) the repeat collection (lines 195-219) does not exist (well I think so, I haven't check the data for this current patch). The boolean at 192 should be false.
https://github.com/koliva8245/Heroes.ReplayParser/blob/27838560be8e08c3ba524a1cb99968769d334fa2/Heroes.ReplayParser/MPQFiles/ReplayServerBattlelobby.cs#L192-L219

**Comment by MGatner** [comment]
Ahh that makes a lot more sense! Thanks for clarifying. The strings were so definitive I thought they were coming from your HeroesDataParser somehow, but I couldn't figure it out.
The missing collection was the main thing hanging me up since that was the only indicative line about how to determine observer versus player ("most likely an observer").
I'm working in PHP, so (for better and worse) binary strings are both strings and binary which makes finding everything quite easy. After the initial binary parse I regex each TId (/T:[0-9]+#[0-9]{3}/), then locate the following BattleTag (/#[0-9]{4,8}/) and work backwards until I hit a non-character byte. What I've been working with is everything between TId and BattleTag listed as bits - I'll keep gathering files with known attributes to see if I can make some senes of them.

**Comment by koliva8245** [comment]
If you aren't using one now, a hex editing tool helps with the parsing, such as [Hexinator](https://hexinator.com/).

Yeah, your right about the observers, that's how you would tell if there were an observer before. Since the players can be in any order, there's no current way to tell if they are an observer, at least in that section. There's probably a bit somewhere I'll have to find.
